# Generated by Django 3.2.9 on 2021-12-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel', '0002_add_supervisor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequest',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fuelrequest',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_nazer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'Agent'), ('u', 'User'), ('s', 'Supervisor')], default='u', max_length=2),
        ),
    ]
